services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_INTERNAL_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      BASE_URL: ${BASE_URL}
    expose:
      - ${PORT}
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/letsencrypt
      - ./ssl-logs:/var/log/letsencrypt
      - ./webroot:/var/www/html
    depends_on:
      - backend
    command: >
      sh -c "nginx -g 'daemon off;'"

  certbot:
    image: certbot/certbot
    volumes:
      - ./ssl:/etc/letsencrypt
      - ./ssl-logs:/var/log/letsencrypt
      - ./webroot:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email bisneto.alberto@gmail.com --agree-tos --no-eff-email -d alberto-api.xyz -d www.alberto-api.xyz
    depends_on:
      - nginx

volumes:
  pgdata: 